Add debug flags and failure handling to workflow

diff --git a/.github/workflows/desc-python-bleed.yml b/.github/workflows/desc-python-bleed.yml
--- a/.github/workflows/desc-python-bleed.yml
+++ b/.github/workflows/desc-python-bleed.yml
@@ -101,6 +101,15 @@ jobs:
       - name: Set up Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v3
+        with:
+          buildkitd-flags: --debug
+
+
+      - name: Run on failure
+        if: failure() && steps.buildx.outcome == 'failure'
+        run: |
+          echo "Buildx setup failed!"
+          exit 1
 
       - name: pull old build
         run: |
